// <auto-generated />
namespace EFCodeFirstApproach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentTrainerIdNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentTrainerIdNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202312010420147_Student-TrainerId-Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
